#配置数据源
spring:
  datasource:
    password: 200312Zwx
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false


mybatis:
  configuration:
    #配置mybatis,支持驼峰命名
    map-underscore-to-camel-case: true
    #日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

